//! The Rust parser must give the same reports as the Python prototype on the
//! synthetic logs in tests/data (generated by tools/gen_parser_fixtures.py).

use std::fs;
use std::path::Path;

use serde_json::Value;

fn check(name: &str) {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let log = fs::read(dir.join(format!("{name}.log"))).expect("log fixture");
    let expected: Value = serde_json::from_str(
        &fs::read_to_string(dir.join(format!("{name}.json"))).expect("json fixture"),
    )
    .expect("valid json");
    let reports = bg_parser::parse_reader(log.as_slice()).expect("in-memory read");
    let mut actual = serde_json::to_value(&reports).expect("serializable");
    // Hero names, the lobby's health and the shop are Rust-only (the Python
    // prototype does not read them); tests/card_names.rs,
    // tests/lobby_health.rs and tests/shop.rs cover them.
    for game in actual.as_array_mut().expect("list of games") {
        let report = game.as_object_mut().expect("report object");
        report.remove("card_names");
        report.remove("start_health");
        report.remove("shop");
        for round in report["rounds"].as_array_mut().expect("rounds") {
            round.as_object_mut().expect("round").remove("health_after");
        }
    }
    assert_eq!(actual, expected, "case {name}");
}

macro_rules! parity {
    ($($name:ident),* $(,)?) => {
        $(#[test] fn $name() { check(stringify!($name)); })*
    };
}

parity!(
    duo_game,
    duo_game_incomplete,
    duo_game_untested_build,
    duo_game_hidden_leg,
    solo_game,
    solo_game_friendly,
    solo_local_eliminated,
    solo_local_eliminated_after_opponent,
    solo_shop_game,
    solo_shop_game_cut,
    not_battlegrounds,
    missing_own_hero,
    missing_entity,
    two_games_new_player_id,
    broken_then_ok,
);

#[test]
fn every_fixture_is_checked() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let count = fs::read_dir(dir)
        .unwrap()
        .filter(|e| {
            e.as_ref()
                .unwrap()
                .path()
                .extension()
                .is_some_and(|x| x == "log")
        })
        .count();
    assert_eq!(count, 15, "add new fixtures to the parity! list");
}

#[test]
fn output_never_contains_player_names() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let log = fs::read(dir.join("two_games_new_player_id.log")).unwrap();
    let reports = bg_parser::parse_reader(log.as_slice()).unwrap();
    let json = serde_json::to_string(&reports).unwrap();
    let text: Vec<String> = reports.iter().map(bg_parser::report::format_text).collect();
    for out in [json, text.join("\n")] {
        assert!(!out.contains("SyntheticPlayer"));
        assert!(!out.contains("Innkeeper"));
    }
}

#[test]
fn games_are_reported_as_they_finish_when_fed_line_by_line() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let log = fs::read_to_string(dir.join("two_games_new_player_id.log")).unwrap();
    let mut reader = bg_parser::LogReader::default();
    let mut finished = Vec::new();
    for line in log.lines() {
        reader.feed(line);
        finished.extend(reader.take_finished());
    }
    assert_eq!(
        finished.len(),
        1,
        "the first game closes when the second starts"
    );
    let rest = reader.finish();
    assert_eq!(rest.len(), 1);
    assert_eq!(rest[0].local_player_id, Some(5));
}

#[test]
fn a_complete_game_is_reported_before_the_next_one_starts() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let log = fs::read_to_string(dir.join("solo_game.log")).unwrap();
    let mut reader = bg_parser::LogReader::default();
    let mut early = Vec::new();
    for line in log.lines() {
        reader.feed(line);
        early.extend(reader.take_completed_current());
    }
    assert_eq!(
        early.len(),
        1,
        "reported once, as soon as STATE=COMPLETE arrives"
    );
    assert_eq!(reader.take_completed_current(), None);
    assert_eq!(early[0], reader.finish()[0]);
}

#[test]
fn an_incomplete_game_is_not_reported_early() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let log = fs::read_to_string(dir.join("duo_game_incomplete.log")).unwrap();
    let mut reader = bg_parser::LogReader::default();
    for line in log.lines() {
        reader.feed(line);
        assert_eq!(reader.take_completed_current(), None);
    }
}

#[test]
fn a_line_too_long_marks_its_game_unsupported_and_spares_the_next() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let solo = fs::read_to_string(dir.join("solo_game.log")).unwrap();
    let cut = solo.find("STATE value=COMPLETE").unwrap();
    let huge = "x".repeat(bg_parser::lines::MAX_LINE + 1);
    let log = format!("{}{huge}\n{}{solo}", &solo[..cut], &solo[cut..]);
    let reports = bg_parser::parse_reader(log.as_bytes()).unwrap();
    let statuses: Vec<_> = reports.iter().map(|r| r.status).collect();
    use bg_parser::report::Status;
    assert_eq!(statuses, [Status::Unsupported, Status::Ok]);
    assert_eq!(reports[0].problems, ["parser error: LineTooLong"]);
}

#[test]
fn extreme_tag_values_do_not_panic() {
    let dir = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests")
        .join("data");
    let log = fs::read_to_string(dir.join("solo_game.log"))
        .unwrap()
        .replace("tag=TURN value=3", "tag=TURN value=-9223372036854775808")
        .replace(
            "tag=DAMAGE value=12",
            "tag=DAMAGE value=-9223372036854775808",
        );
    let reports = bg_parser::parse_reader(log.as_bytes()).unwrap();
    assert_eq!(reports.len(), 1);
}
